const API_KEYS = {
  OPENAI: process.env.REACT_APP_OPENAI,
  SERVICE_ID: process.env.REACT_APP_SERVICE_ID,
  TEMPLATE_ID: process.env.REACT_APP_TEMPLATE_ID,
  AUTORESPONSE_TEMPLATE: process.env.REACT_APP_AUTORESPONSE_TEMPLATE,
  PUBLIC_KEY: process.env.REACT_APP_PUBLIC_KEY,
  SERVICE_ID_FEEDBACK: process.env.REACT_APP_SERVICE_ID_FEEDBACK,
  TEMPLATE_ID_FEEDBACK: process.env.REACT_APP_TEMPLATE_ID_FEEDBACK,
  AUTORESPONSE_TEMPLATE_FEEDBACK: process.env.REACT_APP_AUTORESPONSE_TEMPLATE_FEEDBACK,
  PUBLIC_KEY_FEEDBACK: process.env.REACT_APP_PUBLIC_KEY_FEEDBACK,
};

export { API_KEYS };
export default API_KEYS;
